export const registeredFormFields = {
  active: 'active',
  attachments: 'attachments',
  categories: 'categories',
  created: 'created',
  deleted: 'deleted',
  email: 'email',
  endDate: 'endDate',
  id: 'id',
  locale: 'locale',
  location: 'location',
  name: 'name',
  password: 'password',
  startDate: 'startDate',
  tags: 'tags',
  type: 'type',
  updated: 'updated',
  title: 'title',
  description: 'description',
  content: 'content',
} as const;
