export const registeredFormFields = {
  access_rights: 'access_rights',
  active: 'active',
  address: 'address',
  attachments: 'attachments',
  categories: 'categories',
  city: 'city',
  color: 'color',
  content: 'content',
  country: 'country',
  created: 'created',
  deleted: 'deleted',
  description: 'description',
  district: 'district',
  email: 'email',
  first_name: 'first_name',
  flat_no: 'flat_no',
  id: 'id',
  last_name: 'last_name',
  locale: 'locale',
  location: 'location',
  name: 'name',
  parent: 'parent',
  password: 'password',
  passwordConfirm: 'passwordConfirm', // TODO
  queue: 'queue',
  read: 'read',
  sender: 'sender',
  street: 'street',
  street_no: 'street_no',
  subject: 'subject',
  tags: 'tags',
  title: 'title',
  type: 'type',
  updated: 'updated',
  value: 'value',
  zip: 'zip',

  file_name: 'file_name', // TODO
  file_size: 'file_size', // TODO
  file_type: 'file_type', // TODO
  file: 'file', // TODO
  size: 'size', // TODO

  project: 'project',
  company: 'company',
  phone: 'phone',
  bank: 'bank',
  meta: 'meta',
  keywords: 'keywords',
  robots: 'robots',
  state: 'state',
  debug: 'debug',
  maintenance: 'maintenance',
  messages: 'messages',
  recipients: 'recipients',
  comments: 'comments',
  anonymous: 'anonymous',
  members: 'members',
  ipaddress: 'ipaddress',

  event_start: 'event_start',
  event_end: 'event_end',
  event_location: 'event_location',
  event_address: 'event_address',
} as const;
